services:
  db_auth:
    image: mariadb:latest
    ports:
      - "3307:3306"
    volumes:
      - db_auth_data:/var/lib/mariadb
      - ./init/auth-init.sql:/docker-entrypoint-initdb.d/auth-init.sql
    environment:
      MARIADB_DATABASE: ${AUTH_MARIADB_DATABASE}
      MARIADB_USER: ${AUTH_MARIADB_USER}
      MARIADB_PASSWORD: ${AUTH_MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${AUTH_MARIADB_ROOT_PASSWORD}
    restart: always

  db_resource:
    image: mariadb:latest
    ports:
      - "3308:3306"
    volumes:
      - db_resource_data:/var/lib/mariadb
      - ./init/resource-init.sql:/docker-entrypoint-initdb.d/resource-init.sql
    environment:
      MARIADB_DATABASE: ${RESOURCE_MARIADB_DATABASE}
      MARIADB_USER: ${RESOURCE_MARIADB_USER}
      MARIADB_PASSWORD: ${RESOURCE_MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${RESOURCE_MARIADB_ROOT_PASSWORD}
    restart: always

volumes:
  db_auth_data:
  db_resource_data: