server:
  port: 8888

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${AUTH_SPRING_DATASOURCE_URL}
    username: ${AUTH_SPRING_DATASOURCE_USERNAME}
    password: ${AUTH_SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  time:
    access: ${JWT_ACCESS}
    refresh: ${JWT_REFRESH}

logging.level:
  org.hibernate.SQL: debug